#! /bin/bash
#
# Purpose: Auto merge a pr after tests pass
# Usage: automerge

set -euo pipefail

# So I can keep committing while tests run.
rev="$(git rev-parse HEAD)"
gh run watch --exit-status && git push origin ${rev}:main --tags
