#! /bin/bash
#
# Purpose: Put an issue url to stdout
# Use: gh-url [issue]
#
set -euo pipefail

# tmpdir="$(mktemp -d)"
# finish() {
#   rm -rf "$tmpdir"
# }
# trap finish EXIT

issue="${1:-$(git rev-parse --abbrev-ref HEAD | tr -d -c 0-9)}"
if [[ -z $issue ]]; then
  echo "could not extract issue number from branch name" >&2
  exit 1
fi

exec gh issue view --json url --jq .url $issue
