#! /bin/bash
#
# Purpose: View an issue
# Useage: ghv [issue]
#
set -euo pipefail

# tmpdir="$(mktemp -d)"
# finish() {
#   rm -rf "$tmpdir"
# }
# trap finish EXIT

issue="${1:-$(git rev-parse --abbrev-ref HEAD | tr -d -c 0-9)}"
if [[ -z $issue ]]; then
  echo "could not extract issue number from branch name" >&2
  exit 1
fi

if [[ $# -gt 1 ]]; then
  shift
  exec gh issue view $issue $@
else
  exec gh issue view $issue
fi
